version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "80:80"  # Mapping host port 80 to container port 80
    depends_on:
      - db
    environment:
      - DATABASE_NAME=your_db_name
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
