# Generated by Django 5.1.1 on 2024-09-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_timer',
            new_name='is_timer_enabled',
        ),
        migrations.RemoveField(
            model_name='news',
            name='files',
        ),
    ]
