# Generated by Django 5.1.1 on 2024-09-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkblog',
            name='url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='released_at',
        ),
        migrations.AddField(
            model_name='linkblog',
            name='href',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='linkblog',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='next_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='next_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='next_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='types',
            field=models.CharField(default='center', max_length=100),
        ),
    ]
