# Generated by Django 5.1.1 on 2024-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='news/files/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_news', to='app.imageblog'),
        ),
        migrations.AddField(
            model_name='news',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='file_news', to='app.fileblog'),
        ),
    ]
