# Generated by Django 5.1.1 on 2024-09-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fileblog_alter_news_images_news_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('timer_duration', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='linkblog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='timer_duration',
        ),
        migrations.AddField(
            model_name='fileblog',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileblog',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageblog',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageblog',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkblog',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linkblog',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='timer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timer'),
        ),
    ]
