# Generated by Django 5.1.1 on 2024-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_news_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileblog',
            name='target',
        ),
        migrations.RemoveField(
            model_name='imageblog',
            name='target',
        ),
        migrations.RemoveField(
            model_name='linkblog',
            name='target',
        ),
        migrations.AddField(
            model_name='fileblog',
            name='states',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imageblog',
            name='states',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='linkblog',
            name='states',
            field=models.CharField(default='', max_length=100),
        ),
    ]
