# Generated by Django 5.1.1 on 2024-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_fileblog_target_remove_imageblog_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileblog",
            name="filetype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
