# Generated by Django 5.1.1 on 2024-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_fileblog_filetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileblog",
            name="filetype",
        ),
        migrations.AddField(
            model_name="news",
            name="is_files_in_times",
            field=models.BooleanField(default=False),
        ),
    ]
