# Generated by Django 5.1.1 on 2024-09-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/qimages/'),
        ),
    ]
